In [76]:
from nltk.corpus import brown
import regex as re
import random
from caesarcipher import CaesarCipher
import tensorflow as tf

In [77]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [78]:
sentences = brown.sents()

In [79]:
len(sentences)

57340

In [80]:
import string
remove = string.punctuation
pattern = r"[{}]".format(remove) 
print(remove)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [81]:
sents_cleaned=[]
for i in sentences:
    temp=[]
    for j in i:
        j=re.sub(pattern,"", j)
        if j!="":
            temp.append(j)
    sents_cleaned.append(temp)

In [82]:
X=[]
for i in sents_cleaned:
    str = ' '.join(i)
    rand = random.randint(1,26)
    cipher = CaesarCipher(str,offset=rand)
    temp=[]
    count={}
    for i in range(1,27):
        count[i]=0
    encoded = cipher.encoded
    encoded = encoded.lower()
    for letter in encoded:
        if letter.isalpha():
            count[ord(letter)-97+1] = count.get(ord(letter)-97+1, 0) + 1 
    temp.append(count)
    temp.append(rand)
    X.append(temp)

In [83]:
len(X)

57340

In [84]:
import numpy as np
temp = []
train_list=[]
for i in range(0,len(X)):
    for key,value in X[i][0].items():
        train_list.append(value)  
    temp.append(X[i][1]-1)
train_array = np.array(train_list) 
labels = np.array(temp)

In [85]:
train_array = train_array/26

In [86]:
len(train_list)

1490840

In [87]:
set = train_array.reshape(len(X),26)

In [88]:
len(set)

57340

In [89]:
set.shape

(57340, 26)

In [91]:
labels

array([ 8,  4, 23, ...,  1, 11,  7])

In [92]:
labels.reshape(len(X),1)

array([[ 8],
       [ 4],
       [23],
       ...,
       [ 1],
       [11],
       [ 7]])

In [68]:
from sklearn.model_selection import train_test_split
data_train, data_test, labels_train, labels_test = train_test_split(set, labels, test_size=0.20, random_state=42)

In [69]:
data_train.shape

(45872, 26)

In [70]:
len(data_test)

11468

In [71]:
len(labels_train)

45872

In [72]:
len(labels_test)

11468

In [73]:
print(data_train.shape)
print(labels_train.shape)

print(data_train)
print(labels_train)

(45872, 26)
(45872,)
[[0.03846154 0.03846154 0.         ... 0.         0.         0.        ]
 [0.07692308 0.19230769 0.23076923 ... 0.         0.         0.19230769]
 [0.         0.         0.11538462 ... 0.03846154 0.         0.11538462]
 ...
 [0.         0.         0.03846154 ... 0.         0.15384615 0.15384615]
 [0.23076923 0.03846154 0.         ... 0.03846154 0.         0.07692308]
 [0.15384615 0.03846154 0.26923077 ... 0.42307692 0.42307692 0.88461538]]
[12 13 24 ... 16 21  5]


In [101]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1,input_shape=(26,)),
    tf.keras.layers.Dense(26, activation='sigmoid'),
    tf.keras.layers.Dense(26,activation='sigmoid')
])
model.compile(optimizer='adam',loss=tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=False, reduction=tf.keras.losses.Reduction.AUTO, name="sparse_categorical_crossentropy"))

AttributeError: module 'tensorflow._api.v1.keras.losses' has no attribute 'SparseCategoricalCrossentropy'

In [95]:
model.fit(data_train, labels_train, epochs=100)

Epoch 1/100
45872/45872 [==============================] - 3s 57us/sample - loss: 2.6599 - acc: 0.0328
Epoch 2/100
45872/45872 [==============================] - 2s 51us/sample - loss: 2.6554 - acc: 0.0369
Epoch 3/100
45872/45872 [==============================] - 2s 48us/sample - loss: 2.6508 - acc: 0.0441
Epoch 4/100
45872/45872 [==============================] - 2s 46us/sample - loss: 2.6466 - acc: 0.0337
Epoch 5/100
45872/45872 [==============================] - 3s 55us/sample - loss: 2.6425 - acc: 0.0308
Epoch 6/100
45872/45872 [==============================] - 3s 62us/sample - loss: 2.6390 - acc: 0.0490
Epoch 7/100
45872/45872 [==============================] - 3s 58us/sample - loss: 2.6355 - acc: 0.0336
Epoch 8/100
45872/45872 [==============================] - 2s 49us/sample - loss: 2.6317 - acc: 0.0341
Epoch 9/100
45872/45872 [==============================] - 2s 50us/sample - loss: 2.6287 - acc: 0.0285
Epoch 10/100
45872/45872 [==============================] - 2s 48us/sampl